### ISSUE TITLE
Kernel initialization stalls for up to 5 minutes

### ISSUE THREAD

**Issue by paholden** [kenthartig/Pro3-Linux#3]
Need to figure out why there is a stall and fix it!

**Comment by kenthartig** [comment]
Symptom is that startup will delay almost 5 minutes followed by printing of the following message:
random: crng init done

Forums are talking about enabling haveged

**Comment by kenthartig** [comment]
It appears that adding haveged to the buildroot packages solves the issue. I rebooted the system multiple times without incurring the delay. Boot takes 20-23 seconds to login prompt.

**Comment by paholden** [comment]
I thought you fixed this and pushed the change to the repo already?
